# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy App

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CLIENT_WORKING_DIR : ./client

    strategy:
      matrix:
        node-version: [18.x]
       

    steps:
    - uses: actions/checkout@v3
    - name: Set up nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - run: npm ci
      working-directory: ${{ env.CLIENT_WORKING_DIR }}
    - run: npm run build --if-present
      working-directory: ${{ env.CLIENT_WORKING_DIR }}
    - run: npm run test
      working-directory: ${{ env.CLIENT_WORKING_DIR }}
    
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      working-directory: ${{ env.CLIENT_WORKING_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
