
name: PR Check

on: 
  pull_request: 
    branches: [ main ]
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run tests
      run: npm run test

    - name: Run Build
      run: npm run build
    
